### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by maximiliankolb** [internet-development/www-server-mono#6]
Hi 

I have two suggestions to fine tune versioning the fonts:

- Drop "X.Y.z" in `fonts/` and instead use git for version control
- Release fonts based on tags that are "X.Y.Z", not "Release"

Ideally, there's a GitHub Action that acts on tags and creates an archive associated with the release.

Examples: https://github.com/githubnext/monaspace/tags or https://github.com/ryanoasis/nerd-fonts/tags

**Comment by jimmylee** [comment]
Thanks @maximiliankolb, will do!

**Comment by noClaps** [comment]
https://github.com/ncipollo/release-action - GitHub Releases action that allows you to upload artifacts as well

Since the font files are already in the repository, your steps should be:

- Checkout the repository.
- Zip or Tar the directory with the fonts in it. That should be possible with just Unix commands if you're using `ubuntu-latest`, but there's also probably an action for that.
- Point the release action to the newly created archive.

**Comment by jimmylee** [comment]
Thanks for having our back @noClaps that is very helpful
